### ISSUE TITLE
AutoMRP method machine learning examples dont run, method args seem incomplete

### ISSUE THREAD

**Issue by Braffolk** [retowuest/autoMrP#12]
Hello!

The auto_MrP method examples (https://www.rdocumentation.org/packages/autoMrP/versions/0.99/topics/auto_MrP) do not run. Running this:
```
max_cores <- parallel::detectCores()

# autoMrP with machine learning
ml_out <- auto_MrP(
  y = "YES",
  L1.x = c("L1x1", "L1x2", "L1x3"),
  L2.x = c("L2.x1", "L2.x2", "L2.x3", "L2.x4", "L2.x5", "L2.x6"),
  L2.unit = "state",
  L2.reg = "region",
  bin.proportion = "proportion",
  survey = taxes_survey,
  census = taxes_census,
  gb.L2.reg = TRUE,
  svm.L2.reg = TRUE,
  cores = max_cores
)
```

Results in:
![image](https://user-images.githubusercontent.com/7544836/147406476-ed06b37f-238a-4516-8aea-5eb8095d6222.png)

I made a fork and tried to get things to work. Various required args were missing from either run_classifiers, PCA, SVM or EBMA functions. So this was not the only error. I got things to run, but since I'm not too familiar with the codebase, some fixes might not be correct: https://github.com/kaitumisuuringute-keskus/autoMrP

Are the machine learning examples supposed to not run right now or is it an issue that needs solving?

**Comment by philippbroniecki** [comment]
Thank you for brining this up. These problems arose with the 0.99 update in which we moved the ML classifiers to run_classifiers(). This is fixed now.
