### ISSUE TITLE
Documentation for Data missing

### ISSUE THREAD

**Issue by lleemann** [retowuest/autoMrP#6]
No documentation files for datasets. Should do this for next release.

**Comment by philippbroniecki** [comment]
Data documentation is added. We still need to add the source. We could use the paper or dataverse address.

**Comment by lleemann** [comment]
Data source would be Buttice and Highton, yes?

**Comment by philippbroniecki** [comment]
That's true. Added it and https://www.census.gov/ for the 4 added context-level variables.
